### PR TITLE
Issue40 fixing: code splitting into subfolder/subfiles

### PR DESCRIPTION
**Pull request by maxradx**
Hi,

This Pull Request divides the SlicerCART.py main code into different files/subfolders from code main branch version d2714db (actual main).

**Rationale:** to facilitate further development and organization.
**Difficulty:** to avoid circular imports related to interaction between classes from initial code.
**Why this ‘EPIC’ PR instead of incremential changes?**: interactions between classes makes it more complex to deal with code subdivision in different files, increasing a lot the complexity and expected time to solve the issue.

**What has been done:**
Code division in different files, but otherwise no change in the code. That means that this PR makes using SlicerCART identifcal as from the actual main branch code (so, same use, same functionalities, same bugs but with code splitted). In that context, this PR:

- Introduces subfolder ”utils”. Contains:
      - requirements.py --- listing of all modules required to import for using SlicerCART (can be upgraded in the future)
      - install_python_packages.py --- function that check and install required packages for using SlicerCART
      - global_variables.py --- listing of all global variables in the module
      - __init__.py --- enables all subfolder “utils” content importation

- Introduces subfolder “scripts”. Contains:
      1. InteractingClasses.py --- This NEW file contains all classes that interact with each other from the initial module, including: 
    - SlicerCARTConfigurationSetupWindow
    - SlicerCARTConfigurationInitialWindow
    - ConfigureSegmentationWindow
    - ConfigureSingleLabelWindow
    - ConfigureClassificationWindow
    - ConfigureSingleClassificationItemWindow

N.B.  The scheme below describes the hierarchical organization between interacting classes.

image

N.B.  That means other classes from the initial code do not provide circular import issues. For further development, any file in the scripts repository should contain 1 class. In other words: **1 file == 1 class** ; this will be added in the developer guide.

  2. Multiple pythons files listing one class per file, including: 
- 
  - CompareSegmentVersions.py
  - CustomInteractorStyle.py
  - LoadClassificationWindow.py
  -  LoadSegmentationwindow.py
  - OptionalMethods.py
  - ShowSegmentVersionLegendWindow.py
  - SlicerCARTLogic.py
  - SlicerCARTTest.py
  - Timer.py

Once this PR will be merged into the main branch, then optimized further development can be achieved.

Thanks!

### CODE REVIEW

**Review by AcastaPaloma — DISMISSED** [review]
Everything seems working - PR should be accepted

**Review by AcastaPaloma — DISMISSED** [review]
Where is the check_and_install_python_packages() called?

**Comment by laurentletg** [comment]
Is reloading more complex with this code splitting ? I am looking at the discussion https://discourse.slicer.org/t/is-it-possible-to-split-a-python-extension-into-multiple-files/21713/7 
Was this tested ?

**Comment by maxradx** [comment]
Hi! @Kuan I addressed your comments. Now it should work regarding the check_and_install_python_package(). In fact, you were right: it was not called! (now it is directly in the requirements.py ) @LLG : yes. In the initial PR commit, this was not tested. However, now it is (on my side, no issue); Regarding re-organization, the order of module importing and reloading has been the same as it was originally (linear): no deviation has been made regarding this point.

**Review by AcastaPaloma — APPROVED** [review]
Works great now. Approved.

**Comment by laurentletg** [comment]
Did some tests and reloading also works on my end too (no need to restart Slicer).

**Comment by maxradx** [comment]
Ok great! So, waiting for further feedback/other comments from @LLG about this PR (and/or approval) before merging!

**Comment by laurentletg** [comment]
My main issue right now is how modules are imported. 
The `from module import *` will make the code harder to maintain with potential namespace conflict. I think this should be changed beforme merging the PR. What do you think ?

**Comment by maxradx** [comment]
Ok good point. Available now for calling if you prefer. I ve looked into SlicerHeart. I am not an expert, but a good point is that they import only the functions that they need, at multiple locations. However, this would make very difficult to address in the SlicerCART module since it has been created in one main file so we cannot traceback (without extensive debugging work) when each imported module is used ... (would require weeks) I organized that way so if further modules are imported, then it can be added under the requirements.py file and will be accessible from each other file/main slicer cart in the module. I totally agree that it would be better to use import utils (for example) instead of from utils import * : however, this would also require the use of extensive code reviewing due to how SlicerCART has been initially developed... What do you think? Are you available for a Teams?

**Review by laurentletg — CHANGES_REQUESTED** [review]
My  main issue right now is the import * in the main SlicerCART.py file and modules. 
Unless specific functions or methods need to be imported with `from utils import xxx` and If there is no slicer specific reason to do this I think it is better to import each modules directly and call the specific function/methods/variable with the dot notation [module].[function](args). This require changes to many lines of code but without this we will keep having to search through all files when debugging. 

An alternative is to accept PR as is and create a new issue to be solved as the next PR. 

What do you think ?

**Pull request merged**
